from .IParametric import IParametric
from .IPredictor import IPredictor
from .IRegressor import IRegressor
from .IClassifier import IClassifier
from .ICluster import ICluster
from .IAnomalyRegressor import IAnomalyRegressor
from .IAnomalyClassifier import IAnomalyClassifier
from .IMultipleParametric import IMultipleParametric
from .ISavable import ISavable
from .BaseModel import BaseModel
